CREATE TABLE DOCMETA (DOCID INT PRIMARY KEY, EP INT NOT NULL, FILEID INT NOT NULL);
CREATE TABLE BIZMETA (PID INT PRIMARY KEY, DOCID INT NOT NULL REFERENCES DOCMETA(DOCID), OPID INT NOT NULL);
CREATE INDEX DOCMETA_EP_IX ON DOCMETA(EP);
CREATE INDEX DOCMETA_FILEID_IX ON DOCMETA(FILEID);
CREATE TABLE TERM (TERMID INT PRIMARY KEY, TERM TEXT NOT NULL);
CREATE TABLE DOCTERM (DOCID INT, TERMID INT, CNT INT, PRIMARY KEY(DOCID, TERMID));
CREATE TABLE ASSET (ASSETID INT PRIMARY KEY, ASSETNAME TEXT NOT NULL);
CREATE TABLE QUOTETYPE (QUOTETYPE_ID INT PRIMARY KEY, QUOTETYPE TEXT NOT NULL);
CREATE TABLE ASSET_QUOTE (
	QUOTEID INT PRIMARY KEY,
	ASSETID INT REFERENCES ASSET(ASSETID),
	EX_ASSETID INT REFERENCES ASSET(ASSETID),
	EP INT NOT NULL,
	QUOTETYPE_ID INT REFERENCES QUOTETYPE(QUOTETYPE_ID),
	VAL NUMERIC NOT NULL
);
CREATE INDEX ASSET_QUOTE_EP_IX ON ASSET_QUOTE(EP);
CREATE INDEX ASSET_QUOTE_ASSETID_IX ON ASSET_QUOTE(ASSETID);