CREATE TABLE DOCMETA (DOCID INT PRIMARY KEY, EP INT NOT NULL, FILEID INT NOT NULL);
CREATE TABLE BIZMETA (PID INT PRIMARY KEY, DOCID INT NOT NULL REFERENCES DOCMETA(DOCID), OPID INT NOT NULL);
CREATE INDEX DOCMETA_EP_IX ON DOCMETA(EP);
CREATE INDEX DOCMETA_FILEID_IX ON DOCMETA(FILEID);
CREATE TABLE TERM (TERMID INT PRIMARY KEY, TERM TEXT NOT NULL);
CREATE TABLE DOCTERM (DOCID INT, TERMID INT, CNT INT, PRIMARY KEY(DOCID, TERMID));
CREATE TABLE ASSET (ASSETID INT PRIMARY KEY, ASSETNAME TEXT NOT NULL);
CREATE TABLE QUOTETYPE (QUOTETYPE_ID INT PRIMARY KEY, QUOTETYPE TEXT NOT NULL);
CREATE TABLE QUOTESRC (QUOTESRC_ID INT PRIMARY KEY, QUOTESRC TEXT NOT NULL);

CREATE TABLE ASSET_QUOTE (
	QUOTEID BIGSERIAL PRIMARY KEY,
	ASSETID INT REFERENCES ASSET(ASSETID),
	EX_ASSETID INT REFERENCES ASSET(ASSETID),
	EP0 INT NOT NULL,
	EP1 INT,
	QUOTESRC_ID INT REFERENCES QUOTESRC(QUOTESRC_ID),
	QUOTETYPE_ID INT REFERENCES QUOTETYPE(QUOTETYPE_ID),
	VAL NUMERIC NOT NULL,
	UNIQUE(ASSETID, EX_ASSETID, EP0, EP1, QUOTESRC_ID, QUOTETYPE_ID)
);

CREATE INDEX ASSET_QUOTE_EP0_IX ON ASSET_QUOTE(EP0);
CREATE INDEX ASSET_QUOTE_ASSETID_IX ON ASSET_QUOTE(ASSETID);
CREATE INDEX ASSET_QUOTE_QUOTESRC_ID_IX ON ASSET_QUOTE(QUOTESRC_ID);